# Name your project! dbt assumes this is the name of your project.
name: 'bikesharing_snow'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'user'

# These configurations apply to your models.
# You can define different configurations for different paths:
#   - models/staging/
#   - models/marts/
models:
  bikesharing_snow: # This should match the 'name' of your project above
    # The + sign tells dbt to apply this config to all subdirectories
    +materialized: view # Default materialization for all models is 'view'
    staging:
      +materialized: view # Staging models will be views
      +schema: staging    # Staging models will be built in the 'staging' schema
    marts:
      +materialized: table # Marts models will be tables
      +schema: marts      # Marts models will be built in the 'marts' schema

